export const DOCUMENT_VECTOR_STORE_CONFIG = Symbol("DOCUMENT_VECTOR_STORE_CONFIG");

export const MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024;
export const MAX_FILE_SIZE_DISPLAY = "50MB";
export const S3FILE_DOWNLOAD_TIMEOUT_MS = 5 * 60 * 1000;
