export const DEFAULT_ORGANIZATION_OWNER_EMAIL = "owner@sazim.io";
export const DEFAULT_ORGANIZATION_OWNER_PASSWORD = "Password123";

export const ORGANIZATION_OWNER_EMAIL_ENV_KEY = "ORGANIZATION_OWNER_EMAIL";
export const ORGANIZATION_OWNER_PASSWORD_ENV_KEY = "ORGANIZATION_OWNER_PASSWORD";

export const ORGANIZATION_OWNER_FIRST_NAME = "Organization";
export const ORGANIZATION_OWNER_LAST_NAME = "Owner";
export const ORGANIZATION_OWNER_NAME = "Organization Owner";
