import type { EEmailProvider } from "@/common/enums/emails.enums";
import type { EBooleanEnv, EStageEnv } from "@/common/enums/environment-variables.enums";

export interface IEnvironmentVariables {
  NODE_ENV: string;
  STAGE_ENV: EStageEnv;
  DATABASE_URL: string;
  BE_PORT: number;
  BE_WS_PORT: number;
  API_BASE_URL: string;
  API_HEALTH_URL: string;
  AWS_S3_REGION: string;
  AWS_S3_ENDPOINT: string;
  AWS_S3_BUCKET_NAME: string;
  AWS_S3_BUCKET_URL: string;
  AWS_S3_PRESIGN_URL_EXPIRY_IN_MINUTES: number;
  DOCUSEAL_API_KEY?: string;
  EMAIL_PROVIDER: EEmailProvider;
  RESEND_API_KEY?: string;
  MAILHOG_HOST?: string;
  MAILHOG_PORT?: number;
  ENABLE_AUDIT_LOGGING?: EBooleanEnv;
  ENABLE_BULL_BOARD?: EBooleanEnv;
  BULL_BOARD_USERNAME?: string;
  BULL_BOARD_PASSWORD?: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  WEB_CLIENT_BASE_URL: string;
  SEND_FROM_EMAIL: string;
  ORGANIZATION_OWNER_EMAIL?: string;
  ORGANIZATION_OWNER_PASSWORD?: string;
  SESSION_EXPIRES_IN: number;
  SESSION_UPDATE_AGE: number;
  AI_PROVIDER?: string;
  AI_API_KEY?: string;
  AI_DEFAULT_MODEL?: string;
  GOOGLE_GEN_AI_API_KEY?: string;
  AI_GATEWAY_API_KEY?: string;
  OPENAI_API_KEY?: string;
  OPENAI_VECTOR_STORE_ID?: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_WEBHOOK_FORWARD_URL?: string;
  REDIS_HOST?: string;
  REDIS_PORT?: number;
  REDIS_PASSWORD?: string;
  CASL_CACHE_TTL_SECONDS?: number;
  REDIS_QUEUE_PREFIX?: string;
  QUEUE_RETRY_ATTEMPTS?: number;
  QUEUE_RETRY_DELAY?: number;
  QUEUE_COMPLETED_JOB_RETENTION?: number;
  QUEUE_FAILED_JOB_RETENTION?: number;
  QUEUE_PROCESSOR_CONCURRENCY?: number;
  POSTHOG_API_KEY?: string;
  POSTHOG_HOST?: string;
}
