import { IPhoneCountry } from "./PhoneNumberInput.interfaces";

export const PHONE_COUNTRIES: IPhoneCountry[] = [
  { iso: "US", name: "United States", dialCode: "1", flag: "🇺🇸" },
  { iso: "CA", name: "Canada", dialCode: "1", flag: "🇨🇦" },
  { iso: "GB", name: "United Kingdom", dialCode: "44", flag: "🇬🇧" },
  { iso: "AU", name: "Australia", dialCode: "61", flag: "🇦🇺" },
  { iso: "NZ", name: "New Zealand", dialCode: "64", flag: "🇳🇿" },
  { iso: "IE", name: "Ireland", dialCode: "353", flag: "🇮🇪" },
  { iso: "DE", name: "Germany", dialCode: "49", flag: "🇩🇪" },
  { iso: "FR", name: "France", dialCode: "33", flag: "🇫🇷" },
  { iso: "ES", name: "Spain", dialCode: "34", flag: "🇪🇸" },
  { iso: "IT", name: "Italy", dialCode: "39", flag: "🇮🇹" },
  { iso: "PT", name: "Portugal", dialCode: "351", flag: "🇵🇹" },
  { iso: "NL", name: "Netherlands", dialCode: "31", flag: "🇳🇱" },
  { iso: "BE", name: "Belgium", dialCode: "32", flag: "🇧🇪" },
  { iso: "CH", name: "Switzerland", dialCode: "41", flag: "🇨🇭" },
  { iso: "AT", name: "Austria", dialCode: "43", flag: "🇦🇹" },
  { iso: "SE", name: "Sweden", dialCode: "46", flag: "🇸🇪" },
  { iso: "NO", name: "Norway", dialCode: "47", flag: "🇳🇴" },
  { iso: "DK", name: "Denmark", dialCode: "45", flag: "🇩🇰" },
  { iso: "FI", name: "Finland", dialCode: "358", flag: "🇫🇮" },
  { iso: "IS", name: "Iceland", dialCode: "354", flag: "🇮🇸" },
  { iso: "PL", name: "Poland", dialCode: "48", flag: "🇵🇱" },
  { iso: "CZ", name: "Czech Republic", dialCode: "420", flag: "🇨🇿" },
  { iso: "SK", name: "Slovakia", dialCode: "421", flag: "🇸🇰" },
  { iso: "HU", name: "Hungary", dialCode: "36", flag: "🇭🇺" },
  { iso: "RO", name: "Romania", dialCode: "40", flag: "🇷🇴" },
  { iso: "BG", name: "Bulgaria", dialCode: "359", flag: "🇧🇬" },
  { iso: "GR", name: "Greece", dialCode: "30", flag: "🇬🇷" },
  { iso: "TR", name: "Turkey", dialCode: "90", flag: "🇹🇷" },
  { iso: "RU", name: "Russia", dialCode: "7", flag: "🇷🇺" },
  { iso: "UA", name: "Ukraine", dialCode: "380", flag: "🇺🇦" },
  { iso: "BY", name: "Belarus", dialCode: "375", flag: "🇧🇾" },
  { iso: "EE", name: "Estonia", dialCode: "372", flag: "🇪🇪" },
  { iso: "LV", name: "Latvia", dialCode: "371", flag: "🇱🇻" },
  { iso: "LT", name: "Lithuania", dialCode: "370", flag: "🇱🇹" },
  { iso: "MX", name: "Mexico", dialCode: "52", flag: "🇲🇽" },
  { iso: "BR", name: "Brazil", dialCode: "55", flag: "🇧🇷" },
  { iso: "AR", name: "Argentina", dialCode: "54", flag: "🇦🇷" },
  { iso: "CL", name: "Chile", dialCode: "56", flag: "🇨🇱" },
  { iso: "CO", name: "Colombia", dialCode: "57", flag: "🇨🇴" },
  { iso: "PE", name: "Peru", dialCode: "51", flag: "🇵🇪" },
  { iso: "VE", name: "Venezuela", dialCode: "58", flag: "🇻🇪" },
  { iso: "UY", name: "Uruguay", dialCode: "598", flag: "🇺🇾" },
  { iso: "PY", name: "Paraguay", dialCode: "595", flag: "🇵🇾" },
  { iso: "BO", name: "Bolivia", dialCode: "591", flag: "🇧🇴" },
  { iso: "EC", name: "Ecuador", dialCode: "593", flag: "🇪🇨" },
  { iso: "CR", name: "Costa Rica", dialCode: "506", flag: "🇨🇷" },
  { iso: "PA", name: "Panama", dialCode: "507", flag: "🇵🇦" },
  { iso: "DO", name: "Dominican Republic", dialCode: "1", flag: "🇩🇴" },
  { iso: "PR", name: "Puerto Rico", dialCode: "1", flag: "🇵🇷" },
  { iso: "JM", name: "Jamaica", dialCode: "1", flag: "🇯🇲" },
  { iso: "CN", name: "China", dialCode: "86", flag: "🇨🇳" },
  { iso: "JP", name: "Japan", dialCode: "81", flag: "🇯🇵" },
  { iso: "KR", name: "South Korea", dialCode: "82", flag: "🇰🇷" },
  { iso: "TW", name: "Taiwan", dialCode: "886", flag: "🇹🇼" },
  { iso: "HK", name: "Hong Kong", dialCode: "852", flag: "🇭🇰" },
  { iso: "SG", name: "Singapore", dialCode: "65", flag: "🇸🇬" },
  { iso: "MY", name: "Malaysia", dialCode: "60", flag: "🇲🇾" },
  { iso: "ID", name: "Indonesia", dialCode: "62", flag: "🇮🇩" },
  { iso: "TH", name: "Thailand", dialCode: "66", flag: "🇹🇭" },
  { iso: "PH", name: "Philippines", dialCode: "63", flag: "🇵🇭" },
  { iso: "VN", name: "Vietnam", dialCode: "84", flag: "🇻🇳" },
  { iso: "IN", name: "India", dialCode: "91", flag: "🇮🇳" },
  { iso: "PK", name: "Pakistan", dialCode: "92", flag: "🇵🇰" },
  { iso: "BD", name: "Bangladesh", dialCode: "880", flag: "🇧🇩" },
  { iso: "LK", name: "Sri Lanka", dialCode: "94", flag: "🇱🇰" },
  { iso: "NP", name: "Nepal", dialCode: "977", flag: "🇳🇵" },
  { iso: "BT", name: "Bhutan", dialCode: "975", flag: "🇧🇹" },
  { iso: "MV", name: "Maldives", dialCode: "960", flag: "🇲🇻" },
  { iso: "AF", name: "Afghanistan", dialCode: "93", flag: "🇦🇫" },
  { iso: "IR", name: "Iran", dialCode: "98", flag: "🇮🇷" },
  { iso: "IQ", name: "Iraq", dialCode: "964", flag: "🇮🇶" },
  { iso: "SA", name: "Saudi Arabia", dialCode: "966", flag: "🇸🇦" },
  { iso: "AE", name: "United Arab Emirates", dialCode: "971", flag: "🇦🇪" },
  { iso: "QA", name: "Qatar", dialCode: "974", flag: "🇶🇦" },
  { iso: "BH", name: "Bahrain", dialCode: "973", flag: "🇧🇭" },
  { iso: "KW", name: "Kuwait", dialCode: "965", flag: "🇰🇼" },
  { iso: "OM", name: "Oman", dialCode: "968", flag: "🇴🇲" },
  { iso: "YE", name: "Yemen", dialCode: "967", flag: "🇾🇪" },
  { iso: "JO", name: "Jordan", dialCode: "962", flag: "🇯🇴" },
  { iso: "LB", name: "Lebanon", dialCode: "961", flag: "🇱🇧" },
  { iso: "SY", name: "Syria", dialCode: "963", flag: "🇸🇾" },
  { iso: "IL", name: "Israel", dialCode: "972", flag: "🇮🇱" },
  { iso: "EG", name: "Egypt", dialCode: "20", flag: "🇪🇬" },
  { iso: "MA", name: "Morocco", dialCode: "212", flag: "🇲🇦" },
  { iso: "DZ", name: "Algeria", dialCode: "213", flag: "🇩🇿" },
  { iso: "TN", name: "Tunisia", dialCode: "216", flag: "🇹🇳" },
  { iso: "LY", name: "Libya", dialCode: "218", flag: "🇱🇾" },
  { iso: "SD", name: "Sudan", dialCode: "249", flag: "🇸🇩" },
  { iso: "ZA", name: "South Africa", dialCode: "27", flag: "🇿🇦" },
  { iso: "NG", name: "Nigeria", dialCode: "234", flag: "🇳🇬" },
  { iso: "KE", name: "Kenya", dialCode: "254", flag: "🇰🇪" },
  { iso: "ET", name: "Ethiopia", dialCode: "251", flag: "🇪🇹" },
  { iso: "GH", name: "Ghana", dialCode: "233", flag: "🇬🇭" },
  { iso: "UG", name: "Uganda", dialCode: "256", flag: "🇺🇬" },
  { iso: "TZ", name: "Tanzania", dialCode: "255", flag: "🇹🇿" },
  { iso: "ZW", name: "Zimbabwe", dialCode: "263", flag: "🇿🇼" },
  { iso: "ZM", name: "Zambia", dialCode: "260", flag: "🇿🇲" },
  { iso: "RW", name: "Rwanda", dialCode: "250", flag: "🇷🇼" },
  { iso: "SN", name: "Senegal", dialCode: "221", flag: "🇸🇳" },
  { iso: "CI", name: "Ivory Coast", dialCode: "225", flag: "🇨🇮" },
  { iso: "CM", name: "Cameroon", dialCode: "237", flag: "🇨🇲" },
  { iso: "AO", name: "Angola", dialCode: "244", flag: "🇦🇴" },
  { iso: "MZ", name: "Mozambique", dialCode: "258", flag: "🇲🇿" },
];

export const DEFAULT_PHONE_COUNTRY_ISO = "US";
export const MIN_PHONE_NATIONAL_DIGITS = 6;
export const MAX_PHONE_NATIONAL_DIGITS = 15;
