ARG NODE_VERSION=22.21
ARG BUN_VERSION=1.3.0

# Base stage for installing dependencies
FROM oven/bun:${BUN_VERSION}-alpine as BASE

WORKDIR /usr/src/

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN apk add --no-cache git npm \
  && npm install -g pnpm@10.29.3 \
  && pnpm install --frozen-lockfile \
  && pnpm store prune

# Build stage
FROM oven/bun:${BUN_VERSION}-alpine AS BUILD

WORKDIR /usr/src/

COPY --from=BASE /usr/src/node_modules ./node_modules
COPY . .
RUN apk add --no-cache git curl python3 alpine-sdk npm \
  && npm install -g @mapbox/node-pre-gyp \
  && bun run build:bun

# Rebuild native modules like argon2
RUN apk add --no-cache build-base python3 \
  && node-pre-gyp rebuild -C /usr/src/node_modules/argon2

# Production stage
FROM oven/bun:${BUN_VERSION}-alpine AS PRODUCTION

WORKDIR /usr/src/

COPY --from=BUILD /usr/src/package.json /usr/src/pnpm-lock.yaml /usr/src/pnpm-workspace.yaml /usr/src/.npmrc ./

RUN apk add --no-cache npm \
  && npm install -g pnpm@10.29.3 \
  && pnpm install --prod --frozen-lockfile --ignore-scripts \
  && pnpm store prune

COPY --from=BUILD /usr/src/dist ./dist
COPY --from=BUILD /usr/src/infra ./infra
COPY --from=BUILD /usr/src/node_modules/argon2/lib ./node_modules/argon2/lib
COPY --from=BUILD /usr/src/tsconfig.bun.json ./tsconfig.bun.json

# Set environment variable to indicate Bun is being used
ENV RUNTIME=bun

ENTRYPOINT [ "/bin/sh", "./infra/entrypoints/entrypoint.bun.sh" ]
